### ISSUE TITLE
What to do about empty sequences and mappings?

### ISSUE THREAD

**Issue by gvx** [crdoconnor/strictyaml#10]
I've been writing a `Dumper` that outputs data conforming to strictyaml, and in my testing of it's behaviour, I've found a problem: the only way to represent empty sequences and mappings in YAML is with flow style, which strictyaml disallows. I don't really know any way around making an exception for `[]` and `{}`, though, aside from just refusing to dump empty lists and dicts.

**Comment by crdoconnor** [comment]
Good question. How about this::

    load("x:", Map({"x": Seq(Str())}) | EmptySeq())) == {"x": []}

    load("x:", Map({"x": MapPattern(Str(), Str())}) | EmptyMap())) == {"x": {}}

**Comment by gvx** [comment]
I assume you mean

    load("x:", Map({"x": Seq(Str()) | EmptySeq()})) == {"x": []}
    load("x:", Map({"x": MapPattern(Str(), Str()) | EmptyMap()})) == {"x": {}}

? If so, I'm perfectly fine with emitting nothing for empty lists and dicts.

**Comment by crdoconnor** [comment]
oops, yeah that. I was anyway thinking of creating a null type and this is almost the same thing.

Let me ponder this for a day or so though before implementing. I need to think through the implications.

**Comment by crdoconnor** [comment]
Still not sure if this is the best approach, but anyway: 58bba77cac264900e3b3ffa9695d8c5cb5da7fd4
