### ISSUE TITLE
Question: can a validator know whether a string has quotes in the yaml source?

### ISSUE THREAD

**Issue by justvanrossum** [crdoconnor/strictyaml#103]
I'm trying to write a custom validator for a scalar in which I would like to be able to know whether the value I'm looking at has quotes in the yaml source or not. Example yaml:

```yaml
a: foo
b: "foo"
```

However, in my `validate_scalar(chunk)` method, I can't seem to find that information from the `chunk` object: all I find is the "clean" string "foo" as `chunk.contents`. Am I missing something or is it too late in the process for a validator to know that?

Put another way, I'd like (something like) `MyValidator()|Str()` to go into the `Str()` branch if the original value is quoted, even if the clean value would be valid for `MyValidator()`.

**Comment by crdoconnor** [comment]
It's too late in the validator process to know I'm afraid :(

**Comment by justvanrossum** [comment]
Thanks, that's good to know.
