### ISSUE TITLE
No reference for "YAML 2.0" (or typo)

### ISSUE THREAD

**Issue by FiloSottile** [crdoconnor/strictyaml#109]
One of the FAQ is "Why not use the YAML 2.0 standard?"

A Google search for "YAML 2.0" doesn't turn up anything authoritative, and the latest official spec seems to be YAML 1.2.

If it's not a typo for YAML 1.2, it could use a link to the spec.

**Comment by crdoconnor** [comment]
yes it should be 1.2, I'm not sure why I put 2.0. sorry!
