### ISSUE TITLE
How to specify an empty list or an empty dict?

### ISSUE THREAD

**Issue by kynnjo** [crdoconnor/strictyaml#124]
It often happens that the empty list (resp., an empty dictionary) is a valid value for a list-valued (resp. dict-valued) parameter, respectively.

**Q:** How does one specify an empty list and an empty dict with strictyaml?

I tried both:

```
empty_list_ok: []
```

and

```
empty_dict_ok: {}
```

...but the parser raises an exception in either case.

**Comment by kynnjo** [comment]
I found about specifying schemas featuring strictyaml.EmptyList and strictyaml.EmptyMap.

**Comment by crdoconnor** [comment]
haha, i was just about to share. glad you found it :+1:

**Comment by shoogle** [comment]
Presumably you can also make the list or dict's key [optional](https://hitchdev.com/strictyaml/using/alpha/compound/optional-keys/), and specify `[]` or `{}` as the [default value](https://hitchdev.com/strictyaml/using/alpha/compound/optional-keys-with-defaults/) it should use if the key not present in a particular StrictYAML document.

**Comment by crdoconnor** [comment]
Unfortunately not. Flow style [] and {} are not valid in strictyaml:
https://hitchdev.com/strictyaml/why/flow-style-removed/

**Comment by shoogle** [comment]
@crdoconnor, but the default values are specified in the schema, so `[]` and `{}` would be Python syntax, not YAML syntax. 

Something like this:

```python
from strictyaml import Map, Int, Optional
schema = Map({"a": Int(), Optional("b", default={}): Map(), })
```
Notice how `default={}` is used to specify that the map called `b` is empty by default.

However, when I try it I get `TypeError: __init__() missing 1 required positional argument: 'validator'`.
