### ISSUE TITLE
How to define schemas for maps that allow either extraneous keys or missing keys?

### ISSUE THREAD

**Issue by kynnjo** [crdoconnor/strictyaml#125]
The only way I know to define a schema for a map (dict) often makes the validation done by `strictyaml.load` with such a schema stricter than I want it to be.

In particular, validation with such schemas fail if (1) the input includes a key not explicitly mentioned in the schema; or (2) the input lacks a key explicitly mentioned in the schema.  I would like to know how to relax these restrictions (including how to relax each of them independently).

(Below I give a lot more detail about this question, but if the description above is clear enough, there is no need to read the remainder of this post.)

By way of example, below I define three YAML strings:

```
yaml_compliant = '''
A: xyz
B: 42
C: True
D:
  - foo
  - bar
  - baz
E:
  uno: 1
  dos: 2
  tres: 3
'''.lstrip()

yaml_with_extra_key = '''
A: xyz
B: 42
C: True
D:
  - foo
  - bar
  - baz
E:
  uno: 1
  dos: 2
  tres: 3
AN_ARBITRARY_EXTRANEOUS_KEY: 31415926
'''.lstrip()

yaml_missing_a_key = '''
B: 42
C: True
D:
  - foo
  - bar
  - baz
E:
  uno: 1
  dos: 2
  tres: 3
'''.lstrip()
```

Here is how `strictyaml.load` translates these three strings to Python, by default (i.e., if no schema is specified):

```
In [89]: strictyaml.load(yaml_compliant).data
Out[89]:
OrderedDict([('A', 'xyz'),
             ('B', '42'),
             ('C', 'True'),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', '1'), ('dos', '2'), ('tres', '3')]))])

In [90]: strictyaml.load(yaml_with_extra_key).data
Out[90]:
OrderedDict([('A', 'xyz'),
             ('B', '42'),
             ('C', 'True'),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', '1'), ('dos', '2'), ('tres', '3')])),
             ('AN_ARBITRARY_EXTRANEOUS_KEY', '31415926')])

In [91]: strictyaml.load(yaml_missing_a_key).data
Out[91]:
OrderedDict([('B', '42'),
             ('C', 'True'),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', '1'), ('dos', '2'), ('tres', '3')]))])
```

Now, I define the following schema:

```
strict_schema = strictyaml.Map(dict(
    A=strictyaml.Str(),
    B=strictyaml.Int(),
    C=strictyaml.Bool(),
    D=strictyaml.Seq(strictyaml.Str()),
    E=strictyaml.MapPattern(strictyaml.Str(), strictyaml.Int()),
))
```

With `strict_schema`, `strictyaml.load` translates the string `yaml_compliant` into Python as shown below

```
In [93]: strictyaml.load(yaml_compliant, schema=strict_schema).data
Out[93]:
OrderedDict([('A', 'xyz'),
             ('B', 42),
             ('C', True),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', 1), ('dos', 2), ('tres', 3)]))])
```

On the other hand, with `strict_schema`, `strictyaml.load` raises the following exception when processing `yaml_with_extra_key`:

```
In [94]: strictyaml.load(yaml_with_extra_key, schema=strict_schema).data
YAMLValidationError: while parsing a mapping
unexpected key not in schema 'AN_ARBITRARY_EXTRANEOUS_KEY'
  in "<unicode string>", line 12, column 1:
    AN_ARBITRARY_EXTRANEOUS_KEY: '31 ...
    ^ (line: 12)
```

Likewise, with `strict_schema`, `strictyaml.load` raises the following exception when processing `yaml_missing_a_key`:

```
In [95]: strictyaml.load(yaml_missing_a_key, schema=strict_schema).data
YAMLValidationError: while parsing a mapping
  in "<unicode string>", line 1, column 1:
    B: '42'
     ^ (line: 1)
required key(s) 'A' not found
  in "<unicode string>", line 10, column 1:
      tres: '3'
    ^ (line: 10)
```

I would like to define three new schemas `semi_strict_schema_extraneous_ok`, `semi_strict_schema_missing_ok`, and `lax_schema` that avoid either or both of these types of validation errors.  In brief, `semi_strict_schema_extraneous_ok` should validate `yaml_with_extra_key` but fail on `yaml_missing_a_key`; conversely, `semi_strict_schema_missing_ok` should validate `yaml_missing_a_key` but fail on `yaml_with_extra_key`; and, finally, `lax_schema` should validate both `yaml_with_extra_key` and `yaml_missing_a_key`.  Furtheremore, for these three new schemas, wherever they are more permissive than `strict_schema`, they should, loosely speaking, produce the same result as what `strictyaml.load` produces for the same YAML string when no schema is specified.

Below I give a more precise descriptions of how these schemas should behave.

First, all four schemas should handle `yaml_compliant` in the same way.  In other words, the values of the four expressions below should all be identical:

```
strictyaml.load(yaml_compliant, schema=strict_schema).data
strictyaml.load(yaml_compliant, schema=semi_strict_schema_extraneous_ok).data
strictyaml.load(yaml_compliant, schema=semi_strict_schema_missing_ok).data
strictyaml.load(yaml_compliant, schema=lax_schema).data
```

..., and, as already stated, this value should be

```
OrderedDict([('A', 'xyz'),
             ('B', 42),
             ('C', True),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', 1), ('dos', 2), ('tres', 3)]))])
```

The value of the two expressions below should be identical

```
strictyaml.load(yaml_with_extra_key, schema=semi_strict_schema_extraneous_ok).data
strictyaml.load(yaml_with_extra_key, schema=lax_schema).data
```

and equal to

```
OrderedDict([('A', 'xyz'),
             ('B', 42),
             ('C', True),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', 1), ('dos', 2), ('tres', 3)])),
             ('AN_ARBITRARY_EXTRANEOUS_KEY', '31415926')])
```

The value of the two expressions below should be identical

```
strictyaml.load(yaml_missing_a_key, schema=semi_strict_schema_missing_ok).data
strictyaml.load(yaml_missing_a_key, schema=lax_schema).data
```

and equal to

```
OrderedDict([('B', 42),
             ('C', True),
             ('D', ['foo', 'bar', 'baz']),
             ('E', OrderedDict([('uno', 1), ('dos', 2), ('tres', 3)]))])
```

The evaluations of expressions

```
strictyaml.load(yaml_missing_a_key, schema=strict_schema).data
strictyaml.load(yaml_missing_a_key, schema=semi_strict_schema_extraneous_ok).data
```

should each fail with the error

```
YAMLValidationError: while parsing a mapping
  in "<unicode string>", line 1, column 1:
    B: '42'
     ^ (line: 1)
required key(s) 'A' not found
  in "<unicode string>", line 10, column 1:
      tres: '3'
    ^ (line: 10)
```

The evaluations of expressions

```
strictyaml.load(yaml_with_extra_key, schema=strict_schema).data
strictyaml.load(yaml_with_extra_key, schema=semi_strict_schema_missing_ok).data
```

should each fail with the error

```
YAMLValidationError: while parsing a mapping
unexpected key not in schema 'AN_ARBITRARY_EXTRANEOUS_KEY'
  in "<unicode string>", line 12, column 1:
AN_ARBITRARY_EXTRANEOUS_KEY: '31 ...
^ (line: 12)
```

**Comment by crdoconnor** [comment]
Have you tried load with loose schema and .revalidate(strict_schema) ? (doc page : https://hitchdev.com/strictyaml/using/alpha/howto/revalidation/ )

**Comment by crdoconnor** [comment]
Quite often I will use:

document = load(yaml_string, MapPattern(Str(), Str())

document['example1'].revalidate(Int())
document['example2'].revalidate(Date())

**Comment by kynnjo** [comment]
@crdoconnor: Thank you, I will try these suggestions.

**Comment by crdoconnor** [comment]
No problem. Feel free to reopen if you are still having problems.
