### ISSUE TITLE
Allow flow style for empty list/dict

### ISSUE THREAD

**Issue by kluelesskk** [crdoconnor/strictyaml#127]
AFAIK, the only way to specify an empty dict or list (when not using a schema) in YAML is as {} or []. However, strictyaml rejects these by default as being flow style. This then forces the client to allow flow style globally, when we only want to be able to read in these empty dict or list.

If we were to whitelist them, consider also relaxing the indentation rule. Currently this fails as being incorrectly indented:
```
foo:
  bar: 1
baz: {}
```

**Comment by crdoconnor** [comment]
Are you using validators?

You can tell strictyaml that an empty string is an empty list or dict and
it will parse it as such:

https://hitchdev.com/strictyaml/using/alpha/scalar/empty/


Does that help?

**Comment by crdoconnor** [comment]
I didn't want to enable flow style for this one specific use case because

#1 having just one way of specifying emptiness is preferable to having 3.
This will also help aid understanding for non programmers (who will more
easily understand "emptiness" than "empty dict")

#2 whether it meant empty dict or empty list or empty string is something
that ought to be easily derived from context.

**Comment by kluelesskk** [comment]
Thanks, I guess your reasoning makes sense. I'm using a schema validator external to the yaml parser, and I don't want to lift the schema into the parser. I guess the best approach in that case would be to have the external validator normalize nulls into empty lists or dicts, in the same way that it would already normalize strings into numbers.

**Comment by crdoconnor** [comment]
Yes, that would make sense - without a validation an empty string could be
transformed into either an empty dict or list in a post processing step.

It's also possible (& not too difficult) to programmatically generate a
schema if you have a schema in a different, easily parseable form and want
to translate it.

**Comment by kluelesskk** [comment]
Thanks for the suggestions, I'm all good here.
