### ISSUE TITLE
extraction of parsed data still contains ruamel scalarstrings

### ISSUE THREAD

**Issue by eulores** [crdoconnor/strictyaml#135]
#### Bug
I was expecting this expression

```python
print(type(load('- >\n hello', Seq(Str())).data[0]))
```

to return a `list` of `str`

Instead it returns a `list` of `ruamel.yaml.scalarstring.FoldedScalarString`

This bug is annoying if the data is used for pickling and unpickling later down the chain, as the process doing the unpickling does not accept anything other than `dict`, `list` or `str`, and raises an exception caused by the `FoldedScalarString`

**Comment by crdoconnor** [comment]
try using  .data?

**Comment by crdoconnor** [comment]
oops you did sorry let me take a look a bit later

**Comment by eulores** [comment]
Just guessing, but maybe this is due to strictyaml using ruamel yaml with roundtrip?

If the **roundtrip mode** of ruamel is initialized, then 
```python
print(type(yaml.load('- >\n hello')[0]))
```
returns `<class 'ruamel.yaml.scalarstring.FoldedScalarString'>`

---
If the **safe mode** of ruamel is initialized, then 
```python
print(type(yaml.load('- >\n hello')[0]))
```
returns `<class 'str'>`

**Comment by crdoconnor** [comment]
yes, that's correct.

**Comment by crdoconnor** [comment]
i think i've got a fix, although i've had a couple of glasses of wine so i'm not sure if i should trust myself to push it out.

**Comment by crdoconnor** [comment]
Fixed in version 1.3.2

**Comment by eulores** [comment]
that was fast!!! Thanks for the fix :-)

**Comment by crdoconnor** [comment]
no problem. it was quite a bad bug. thanks for pointing it out. i've added you to the contributors list.
