### ISSUE TITLE
.as_yaml() ignores schema and numerical strings are not quoted

### ISSUE THREAD

**Issue by petermorrow** [crdoconnor/strictyaml#137]
Here's an example where `1` should be quoted to ensure it's a string.

```python
>>> from strictyaml import as_document, Map, Str

>>> schema = Map(dict(x=Str()))
>>> document = as_document(dict(x='1'), schema=schema)
>>> print(document.as_yaml())
x: 1
```

Expected behavior
```python
>>> print(document.as_yaml())
x: '1'
```

**Comment by crdoconnor** [comment]
This is intended behavior. If you parse this dict back using the same schema it should parse as {"a": "1"}.

Everything is a string by default in StrictYAML. Quotes are required only for syntactic disambiguation. For example:

```
>>> document = as_document(dict(x='a : b'), schema=schema)
>>> print(document.as_yaml())
x: 'a : b'
```

**Comment by petermorrow** [comment]
I need to pass this yaml document to another tool that does not use StrictYAML and will throw a validation error instead of marshaling values to their expected types.

https://github.com/yaml/pyyaml will automatically quote numerical strings when using `yaml.dump`. For example:

```python
>>> import yaml
>>> import io

>>> f = io.StringIO()
>>> yaml.dump(dict(x='1'), f)
>>> f.seek(0)
>>> print(f.read())
x: '1'
```

I thought that `.as_yaml()` would be the StrictYAML equivalent to `yaml.dump`.

Does StrictYAML have a method similar to `yaml.dump` that quotes troublesome values like numerical strings?
