### ISSUE TITLE
ScalarValidator equivalent for Compounds / Deserialization

### ISSUE THREAD

**Issue by orangelynx** [crdoconnor/strictyaml#150]
Just wanted to shortly ask, in case I'm missing something "obvious".

The way I understand the strictyaml code, it is not intended to have some custom compound validators that could be used to deserialize objects, correct? For example, I could not inherit from `strictyaml.Map` somehow and have a dictionary in the yaml be reduced to a namedtuple object or the like.

I'm trying to do something in the direction of #104 but if I'm correct, the de serialization step would need to be after the schema validation, right?

**Comment by crdoconnor** [comment]
You can create your own custom compound validator in theory, but I wouldn't necessarily encourage it.

The code is pretty nasty and completely undocumented. Whatever you did would probably break in the future when I refactor the nastiness out of compound validation.

Custom compound validation with a clean API was on my internal roadmap but it's a little way off, I'm afraid.
