### ISSUE TITLE
Known + unknown key validation in Map

### ISSUE THREAD

**Issue by jnichols0** [crdoconnor/strictyaml#156]
I have a schema that my project owns but doesn't want to think about changing until our next major version release. It has a two top level keys, one an optional and known string, the other is a required but unknown string that matches a regular expression. I want to do something like the following:

```
my_schema = Map({ Regex( "some_regex" ) : ... ,
                  Optional("some_string") : ... })
```

My understaning is Map wants to use a scalar validator, which wouldn't work with Regex. Running the above right now just throws an error when it gets to the unknown key that I want to match the regex. 

Is there a solution I am overlooking? Is this purposfully not possible? Any help would be greatly appreciated.

I'm using python 3.7.9

**Comment by crdoconnor** [comment]
This is the kind of thing where I would use an initial "loose" schema (e.g.
MapPattern(Str(), Any()) and then write custom code for the fancy part
(keys that match a regex) and then use .revalidate on the contents of those
keys.

**Comment by jnichols0** [comment]
Thanks so much for the quick response. I think I've got a solution working using revalidate. I'll close the issue.
