### ISSUE TITLE
turn on discussions

### ISSUE THREAD

**Issue by julie777** [crdoconnor/strictyaml#171]
I think having discussions for the project enabled would be great for discussing things that aren't bugs or a specific enhancement request.

Do you prefer using issues for discussion?

**Comment by crdoconnor** [comment]
Hi julie sorry I didn't get back to you earlier with all of your comments. I have had an absolutely hellish month for a number of reasons and I haven't had time to attend to strictyaml. I do appreciate all of the messages you have sent though.

I have turned on discussions. I will endeavor to get to your comments in the next week or so.

I don't mind issues being used for discussions either though.

**Comment by julie777** [comment]
Thanks
