### ISSUE TITLE
UnicodeEncodeError in Python2.7

### ISSUE THREAD

**Issue by jpscaletti** [crdoconnor/strictyaml#18]
If the YAML file has any non-latin1 character, strictyaml can't load the document.

Test case:

````python
# coding=utf-8
import strictyaml

yaml = u'''
name: Olé
age: 38
'''
strictyaml.load(yaml).data
````

**Comment by jpscaletti** [comment]
If python2.7 isn't supported, then the problem is that the `setup.py` says otherwise

**Comment by crdoconnor** [comment]
Thanks for pointing this out, will fix this today.

**Comment by crdoconnor** [comment]
Should be fixed now, but if you see any more problems, please let me know. Thanks once again for reporting the issue!
