### ISSUE TITLE
Date vs Datetime

### ISSUE THREAD

**Issue by honzajavorek** [crdoconnor/strictyaml#191]
Hi, is there an easy way to have something like Date? Similar to existing Datetime, but forces the value to be just date, no time, and returns an instance of `datetime.date()`.

**Comment by crdoconnor** [comment]
Hi @honzajavorek no there isn't but it is pretty easy to create one.

```python
from datetime import datetime

class DateValidator(ScalarValidator):
    def validate_scalar(self, chunk):
        return datetime.strptime(chunk.contents, '%Y-%m-%d').date()
```

validator = DateValidator()

**Comment by honzajavorek** [comment]
Works great, thanks!
