### ISSUE TITLE
Thoughts regarding case-sensitivity of keys

### ISSUE THREAD

**Issue by Racso** [crdoconnor/strictyaml#201]
Hi! Per title: do you have any thoughts regarding the case-sensitivity of keys?

YAML is case-sensitive, so this is valid YAML:

```
name: A
Name: B
```

However, my opinion is that this is as dangerous as allowing duplicate keys (which strictyaml doesn't allow for good reasons). Therefore, I think that the loading of keys should be case-insensitive (so my example should throw a `DuplicateKeysDisallowed` exception).

Is strictyaml case-sensitive or case-insensitive? If it is case-sensistive, is there a reason?

Thanks!

**Comment by crdoconnor** [comment]
hi, its case insensitive but I can see your point.

**Comment by crdoconnor** [comment]
sorry, I mean it's case sensitive

**Comment by crdoconnor** [comment]
I think it's kind of a moot point though, if you have a schema.

If you use Map, and you specify "name" it will reject "Name".

If you use MapPattern, you can use a case insensitive validator for the key
if you want.

If you dont use a schema... you should!

**Comment by Racso** [comment]
Sure. A schema fixes the issue.

But not having a schema is also valid. Shouldn't that case be protected by the strict ruling?

Another way of analyzing it: do you see any advantages of having case sensitivity over not having it? Do you see any use cases where the advantages overcome the risks?

**Comment by shoogle** [comment]
Here's are two examples of where case-sensitivity is useful/essential:

### 1. Dictionary

```yaml
dry: Free from liquid or moisture.
DRY: Acronym for "Don't Repeat Yourself".
```

### 2. Unix filesystem

```yaml
etc:
  fstab: A special file that defines mountpoints for disk partitions.
  FSTAB: A regular file.
```

StrictYAML needs to be case-sensitive to support these use-cases.

If you have a particular use-case that requires *case-insensitivity* (e.g. files on an NTFS or APFS filesystem) then I think you should enforce that in the schema or at the application level rather than making it an inherent part of the StrictYAML standard.

**Comment by Racso** [comment]
Thanks. Those are solid examples. 

Small clarification: please note that I'm not proposing to _do_ anything to the standard. I just wanted to read thoughts about the topic in the context of StrictYAML.
