### ISSUE TITLE
Implicit Typing in StrictYAML

### ISSUE THREAD

**Issue by vnc5** [crdoconnor/strictyaml#22]
Consider this YAML:
```yaml
array:
  - string 1!
  - string: 2?
```
Which parses into this:
```python
{'array': ['string 1!', {'string': '2?'}]}
```
The value determines its type.
You've eliminated this behavior for primitive types:
```yaml
python: 3.5.3
postgres: 9.3
```
Both are strings. But there is still implicit typing between string and map.

An array element syntax like:
```yaml
array:
  -
  key1: value1
  key2: value2
  -
  key1: value1
  key2: value2
  - some: text
```
would fix this behavior but then it wouldn't be a subset of YAML anymore 😄

**Comment by vnc5** [comment]
This also happens in objects:
```yaml
key: key2: value
```
`ruamel.yaml.scanner.ScannerError: mapping values are not allowed here`

**Comment by crdoconnor** [comment]
I'm not exactly sure what it is you are proposing here. Could you clarify?

**Comment by vnc5** [comment]
In the FAQ it says that StrictYAML removes implicit typing, but this is still a thing as shown above.
I've seen YAML files like:
```yaml
ssh-authorized-keys:
  - sha-rsa AAAB3Nz...
  - sha-rsa AAAB3Nz...
```
In this case you are kinda lucky because the syntax of the authorized_keys file doesn't contain a colon. Every element in ssh-authorized-keys is a string.
But if it would contain a colon like `sha-rsa: AAAB3Nz...` those elements will turn into maps but you would assume that the elements are still strings.

**Comment by crdoconnor** [comment]
Not if you use validators.

**Comment by vnc5** [comment]
```yaml
key: key: value
```
```python
print(load(yaml_string, Map({"key": Str()})).data)
```
```
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 1, column 9:
    key: key: value
            ^ (line: 1)
```

**Comment by crdoconnor** [comment]
??? If you want to represent that you can:

```yaml
key: |
  key: value
```
```python
>>> print(load(yaml_string, Map({"key": Str()})).data)
{"key": "key: value"}
```

**Comment by vnc5** [comment]
I know

**Comment by crdoconnor** [comment]
So... ?

**Comment by vnc5** [comment]
So now you have:
- Implicit Typing: `key: key: value` vs `key: key : value`
- Explicit Typing: `key: 'key: value'` and the pipe syntax
- Neither non-programmer friendly nor programmer friendly

**Comment by crdoconnor** [comment]
>Tell a non-programmer that url2 doesn't work.

That's what the error message with line numbers and a code snippet is for.

**Comment by vnc5** [comment]
So we have a parser error determined by the content of a value:
`key: key: value` vs `key: key:value`
Implicit Typing determined by the content of a value in valid YAML:
```yaml
array:
  - key: value
  - key:value
```
which will lead to errors in unvalidated programs.
Validation error determined by the content of a value:
```yaml
array:
  - key: value
```
```
strictyaml.exceptions.YAMLValidationError: when expecting a str
found mapping/sequence
  in "<unicode string>", line 2, column 1:
    - key: value
    ^ (line: 2)
```

**Comment by crdoconnor** [comment]
I think we're going around in circles now.
