### ISSUE TITLE
Add label to load function

### ISSUE THREAD

**Issue by crdoconnor** [crdoconnor/strictyaml#26]
Feature requested in https://github.com/gjcarneiro/yacron/issues/4

Example:

    try:
        doc = strictyaml.load(data, CONFIG_SCHEMA, label=path).data
    except YAMLValidationError as ex:
        print(ex)

    strictyaml.exceptions.YAMLValidationError: while parsing a mapping
    unexpected key not in schema 'killTimeoutx'
      in "/path/to/whatever.yaml", line 73, column 1:
          killTimeoutx: '0.5'
        ^ (line: 73)

**Comment by gjcarneiro** [comment]
+1
