### ISSUE TITLE
[query] What is the set relationship between StrictYAML and JSON?

### ISSUE THREAD

**Issue by kwill** [crdoconnor/strictyaml#27]
It is clear that:
* StrictYAML is a subset of YAML
* JSON is a subset of YAML

...but what is the relationship between StrictYAML and JSON?

1. All JSON is a subset of StrictYAML
2. There is some meaningful overlap ("StrictJSON", readable by both StrictYAML and JSON parsers)
3. There is some overlap, but it doesn't have practical application (readable, but missing essential structures for common use cases)
4. There is no overlap
5. Something else?

...if it is 2, is there an easy way to check that a given StrictYAML string is also JSON parseable? This would allow me to use one library (StrictYAML) to generate and parse all my JSON and YAML data.

**Comment by crdoconnor** [comment]
4. There's no overlap. The feature (flow style) which make normal YAML a superset of JSON is simply turned off in StrictYAML and the parser will raise a Disallowed exception if you try to use it. The reasoning is in the FAQ.

StrictYAML just parses as dicts, lists and scalar values though (strings by default), so it's perfectly valid to parse a YAML document and dump it out as json::

    import strictyaml
    import json

    my_json = json.dumps(strictyaml.load(my_yaml_document).data)

**Comment by crdoconnor** [comment]
Out of curiosity (and to help improve StrictYAML for others), can I ask what your use case is and how this affected your decision?

**Comment by kwill** [comment]
I'm planning on using StrictYAML to store and validate config values, but I'm aware that many other modules use JSON (including services written in other languages). I wanted to check if/how I could validate JSON data with StrictYAML and/or provide StrictYAML data to JSON consumers and (for no good reason) round-trip JSON data. This is all very abstract, I don't have any concrete implementations yet. Thanks for your response, it looks like it should be manageable. I'll be sure to make comments if I actually do anything interesting!
