### ISSUE TITLE
FAQ has some wonky wording in "What is wrong with explicit syntax typing" section

### ISSUE THREAD

**Issue by Taywee** [crdoconnor/strictyaml#28]
In the [What is wrong with explicit syntax typing in a readable configuration languages](https://github.com/crdoconnor/strictyaml/blob/master/FAQ.rst#what-is-wrong-with-explicit-syntax-typing-in-a-readable-configuration-languages) section, there is this line:

> StrictYAML does require quotation marks for strings that are implicitly converted to other types (e.g. yes or 1.5), but it does require quotation marks for strings that are syntactically confusing (e.g. "{ text in curly brackets }")

Based on the functioning of the module, it seems like this is intended to actually be something more like:

> StrictYAML does not require quotation marks for strings that would be implicitly converted to other types in ordinary YAML (e.g. yes or 1.5), but it does require quotation marks for strings that are syntactically confusing (e.g. "{ text in curly brackets }")

**Comment by crdoconnor** [comment]
Thanks! Sorry, should have done this immediately. It dropped off my radar.
