### ISSUE TITLE
Implement Mapping abstract base class

### ISSUE THREAD

**Issue by sio** [crdoconnor/strictyaml#39]
`YAML` class does already meet almost all requirements of the Mapping abstract base class (`collections.abc.Mapping`). The only missing method is `__iter__`

If you implement that method, `YAML` instances will automatically be considered instances of Mapping ABC - that will enable passing them to third party functions that require generic mappings.

Thank you!

**Comment by crdoconnor** [comment]
Implemented in release 0.12.0. Thanks for the feedback @sio!

I'm still not sure if passing YAML objects directly to third party functions is the best idea. I'd use .data to get actual dicts/lists/values first.

**Comment by crdoconnor** [comment]
Yes, but this would mean that YAML sequence and scalar objects would get erroneously identified as mappings/dicts, which would be bad.

Out of curiosity, what's your use case here? Is there some particular reason why you can't use .data?

**Comment by sio** [comment]
Oh, I didn't think of it. Then of course inheriting from Mapping is not an
option.

>
My use case is modifying YAML file (changing values) while retaining
existing comments. The code doing the modification expects any mapping, so
passing the whole YAML object is OK for me. I didn't think this through for
scalar and sequence objects, though. Maybe I'll need to figure out some
kind of workaround for that.
