### ISSUE TITLE
Feature request: Validation of UNIX file path

### ISSUE THREAD

**Issue by fkromer** [crdoconnor/strictyaml#44]
Would you accept a PR which implements syntax validation (based on regular expressions) of UNIX file paths similar to how [Email and Url validators](https://hitchdev.com/strictyaml/using/alpha/scalar/email-and-url/) work?

**Comment by crdoconnor** [comment]
Yep, I'd love that.

**Comment by crdoconnor** [comment]
Please make sure the PR comes accompanied with a story that verifies and describes the change though. E.g. modify this story: https://github.com/crdoconnor/strictyaml/blob/master/hitch/email-url.story

Thanks!

**Comment by crdoconnor** [comment]
FYI i realized earlier that I hadn't been very clear about how to set up a development environment. If that's useful, I've written up instructions here: https://hitchdev.com/approach/contributing-to-hitch-libraries/

**Comment by fkromer** [comment]
UNIX file path validation seems to be a [bit tricky in practice](https://stackoverflow.com/questions/537772/what-is-the-most-correct-regular-expression-for-a-unix-file-path). StrictYaml should probably only do plain syntax validation I guess. Means I wouldn't consider OS and filesystem specifics. Only `/` and `NUL` seem to be invalid UNIX file path characters (`/` is name-separator character). However a regex like `[^\0]+` (one or more characters not `NUL`) could raise a lot of false positives.

**Comment by crdoconnor** [comment]
Interesting. I'm actually not even sure if a NUL character will parse in YAML.

Either way, the fact that damn near everything is apparently a valid file path suggests that just using Str is probably the best approach.

**Comment by fkromer** [comment]
I agree. I'll stick to Str syntax validation for now.

**Comment by crdoconnor** [comment]
Ok cool. I'm closing this for now, but feel free to reopen if you have any new ideas or find anything else of interest.
