### ISSUE TITLE
Bug: Or on deeper structures breaks

### ISSUE THREAD

**Issue by kinkerl** [crdoconnor/strictyaml#51]
Hi, i found a bug when trying to "or" deeper nested structures:

```
from strictyaml import load, Map, MapPattern, Str, Int

yaml="""
configuration: 
  test1:
    helptext: "some text"
  test2:
    helptext: "some other text."
    min: 0
"""

schema = Map(
    {
        "configuration": MapPattern(
            Str(), 
            Map({
                "helptext": Str(), 
            }) | Map({
                "helptext": Str(), 
                "min": Int(), 
            }),
            minimum_keys=1
        ),
    }
)

data = load(yaml, schema=schema)
print(data.data)
```

which results in 

```
strictyaml.exceptions.YAMLValidationError: when expecting an integer
found arbitrary text
  in "<unicode string>", line 5, column 1:
        helptext: some other text.
    ^ (line: 5)
```

the strange thing is, it "works" when the`min` validator is a `Str()` so i guess the validators are applied to the wrong content?

**Comment by crdoconnor** [comment]
Yeah, this is an unfortunate bug. Thank you for bringing it to my attention.

It's a natural side effect of the stateful way in which mappings are parsed via the validator (I did it statelessly for a while but that made validations take an unconscionably long time to parse).

This can, of course, be avoided by using Optional, which is the recommended way of parsing the way you just did:

```
schema = Map(
    {
        "configuration": MapPattern(
            Str(), 
            Map({
                "helptext": Str(), 
                Optional("min"): Int(), 
            }),
            minimum_keys=1
        ),
    }
)
```

I'm considering a 'fix' being to prevent Or validation combinations which include more than one Map. I had originally intended Or validation to solely be used like so:

`"EmptyNone() | Str() | Map({...})"`

Rather than as a way of combining Maps:

`"Map({...}) | Map({....}).`

**Comment by kinkerl** [comment]
Hey, thank you for the response. 

My original usecase and how i found the bug is a little more complex than the example i used above. I don't think i can achieve this with `Optional`:

I want to define and validate a list of components in YAML. A component can be of a certain type (A or B) and each component type can have its own attributes, depending on the type. For example we have for component A:

```
 Map({
    "type": Str(),  # type A
    "helptext": Str(), 
}),
```

And component B looks like this:

```
 Map({
    "type": Str(),  # type B
    "min": Int(), 
    "max": Int(), 
}),
```

And i would like to create list that consists, for example, of three times component A and two times component B and then again tree times component A. The order is not fix, but it is important. (just as a random example, the numbers can change)

Shorter example:
```
 configuration
  component_a:
    type: A
    helptext: "some text"
  component_b:
    type: B
    min: 1
    max: 10
  component_a:
    type: A
    helptext: "some other text"
```


It relativly easy to write the YAML for that but i have a super hard time to find a way to create a schema for that, given that the validator is stateful. 

Do you think it is possible to validate the YAML with the limitations?

**Comment by crdoconnor** [comment]
Yeah, I can create a new mapping type for that over the weekend. Thanks for
sharing with me.

**Comment by crdoconnor** [comment]
I have a similar feature requirement
https://github.com/crdoconnor/strictyaml/issues/41

**Comment by crdoconnor** [comment]
Looks like I won't be able to get it done this weekend, but I'm still working on it.

**Comment by kinkerl** [comment]
No worries. Anything i can help you with?

**Comment by crdoconnor** [comment]
Actually it just occurred to me this morning that what you want is likely
easily achievable using the revalidation feature.

You can use Any for the overall structure and loop through the items
checking to see if type=a/b and applying .revalidate as appropriate using
the relevant Map.

Does that make sense?

**Comment by kinkerl** [comment]
I think i understand what you are getting at but i have zero idea how to do that, yet :)

Essentially, this would move away from a "static" large schema definition to a more dynamic validation, correct?

**Comment by crdoconnor** [comment]
Correct.

This part of the docs might give you an idea of how it could be achieved:

https://hitchdev.com/strictyaml/using/alpha/howto/revalidation/

**Comment by crdoconnor** [comment]
Alternatively I can write up some code this evening that would work for
your use case.

**Comment by kinkerl** [comment]
ha, this actually works well!

I think we should leave the ticket open for the original bug but my problem is solved for now. I can work with that. Thank you very much!

**Comment by crdoconnor** [comment]
Thanks. And thanks once again for pointing it out.

I'm working on preventing the above bug from occurring by preventing the combination of Maps / Seqs using the Or validator. I'll put a message hinting that the end user should use revalidation for their purposes so future users won't fall down the same rabbit hole.

**Comment by crdoconnor** [comment]
OrValidation is now disallowed using multiple MapValidators in version 1.0.1.

**Comment by kumekay** [comment]
I have a small question,
Though it's not stated that project version is following semantic versioning,
my general feeling says that patch version update shouldn't introduce breaking changes.
Do you have some policy about versioning for this project?
