### ISSUE TITLE
Loading to named tuple

### ISSUE THREAD

**Issue by worldmind** [crdoconnor/strictyaml#52]
Hi,
Thanks for interesting project - we live in very strange world, where so basic things like human readable file format has no good and popular solution.
StrictYAML looks like good candidate.
I have a small question/feature request - is it possible to load StrictYAML file not to OrderedDict, but to named tuple?
Where is two reasons for this:
1. It's immutable - for example, it's more safe for global config.
2. It's more readable: you can write `person.name` instead `person['name']`

**Comment by crdoconnor** [comment]
Thanks!

I'm afraid it's not possible to load to named tuple directly. StrictYAML is designed to allow roundtripping, so mutability is built in by default.

That said - it should be relatively straightforward to use something like [this](https://gist.github.com/hangtwenty/5960435) to take the output of .data and replace the dicts with named tuples.

**Comment by worldmind** [comment]
Ok, thanks for answer.
