### ISSUE TITLE
StrictYAMLError should not inherit from YAMLError

### ISSUE THREAD

**Issue by AlexandreDecan** [crdoconnor/strictyaml#6]
Consider the following: 
https://github.com/crdoconnor/strictyaml/blob/master/strictyaml/exceptions.py#L4

`StrictYAMLError` should not inherit from `YAMLError`, allowing people to make a clear distinction between errors that are raised by your library and errors that are raised by the underlying one. 

I know one could simply do:

``` python
try:
  # ...
except YAMLError:
  pass
except StrictYAMLError:
  pass
```

But (1) this implies that `YAMLError` is in the current scope (it is not even exposed by your library, but that's not the point), and (2) `YAMLError` are caught before `StrictYAMLError`.

**Comment by crdoconnor** [comment]
Currently YAMLError is what gets raised for normal parsing errors (syntax errors, etc.) whereas StrictYAMLError is what gets raised if your schema doesn't match the input or if you use one of the prohibited features of YAML.

Ideally there should be one root exception for all of this so users of the library can just put one try/except and get a nicely formatted error that clearly describes the issue that they face. This is why I inherit from YAMLError.

**Comment by crdoconnor** [comment]
Actually that's a good point I should expose ruamel.yaml's YAMLError in strictyaml's __init__.py.

**Comment by AlexandreDecan** [comment]
You should preferably not expose the API of ruamel.yaml, and should preferably declare your own exceptions hierarchy, and automatically convert all ``YAMLError`` from ruamel.yaml to your own exceptions (and please, do make a distinction between errors that are related to YAML and errors that are related to the validation process).

**Comment by crdoconnor** [comment]
Why?

**Comment by AlexandreDecan** [comment]
Because your package will look better as a YAML loader with type safety, less as a YAML validator that imposes to load YAML documents through its API and to manipulate it through one of its dependencies.

**Comment by crdoconnor** [comment]
There's nothing particularly wrong with the way ruamel.yaml loads YAML. It adheres to the spec just fine and it validates what's in the spec just fine and the exceptions it raises are fine. This is why I used it - it's an excellent base to build upon.

strictyaml is not supposed to be a parser in its own right.

**Comment by AlexandreDecan** [comment]
> strictyaml is not supposed to be a parser in its own right.

Currently, it is not possible to:
 - Validate a YAML without loading it with your tool (ala pykwalify).
 - Validate *a YAML* after it has been loaded by ruamel.yaml or pyyaml (ala https://pypi.python.org/pypi/schema). 

So either your provide a feature parity with ruamel.yaml in your ``load`` function, or maybe you should not enforce the use of your ``load`` function?

**Comment by crdoconnor** [comment]
It's not, no. The reason for this is because I wanted to ensure that validation errors included line numbers (and in the future, code snippets) - these things would typically be lost if you used another tool to parse first and then passed the result on.

**Comment by AlexandreDecan** [comment]
I understand, but that means that your validator implies a burden and is not a "drop-in" replacement for ruamel.yaml with a lot of cool stuff about type checking. ;-)
