### ISSUE TITLE
Cannot add keys to existing YAML

### ISSUE THREAD

**Issue by wwoods** [crdoconnor/strictyaml#72]
Bug or feature request, hard to tell.

The following code:

```python
import strictyaml as s
doc = s.load('a: 9', s.Map({ 
    'a': s.Str(), 
    s.Optional('b'): s.Int(),
}))
doc['b'] = 9
```

Fails with: `AttributeError: 'int' object has no attribute 'validator'`.  If, instead, I were to do this:

```python
doc['b'] = s.as_document(9)
```

I get: `YAMLSerializationError: '9' is not a string`

Two things are wrong here: 

1. The first assignment should be perfectly valid.  

2. From the second example, strictyaml has clearly forgotten that the `b` key should be an `Int()`.

Any insight on this?  I suppose I could try to put a patch together... I do appreciate the aims of the strictyaml library.

**Comment by crdoconnor** [comment]
Hi, you shouldn't try to convert 9 into a document. Just do doc["b"] = 9

Alternatively if you feed as_document a schema (i.e. Int()) it will accept
non strings.

**Comment by wwoods** [comment]
Pushed a pull request.  Turned out the mapping's validator wasn't used at all for missing keys, which puts it solidly in the bug category.
