### ISSUE TITLE
Validation where document schema is superset of expected schema

### ISSUE THREAD

**Issue by nchammas** [crdoconnor/strictyaml#81]
I was trying to find out on the [project site](https://hitchdev.com/strictyaml/) whether specifying a schema prevents the document from having additional fields.

In other words, if a document's schema is a superset of the expected schema, is it considered valid?

**Comment by crdoconnor** [comment]
If I'm understanding correctly, the answer is no - you can't have
additional fields. It is possible to have a loose schema which you then
tighten up with revalidate however.

**Comment by nchammas** [comment]
Would it make sense to add this kind of "minimum required schema" validation to StrictYAML?

I don't use StrictYAML today (I just discovered it) but I am thinking about how I would use it to validate a configuration file for a command-line tool. I may want to ensure that certain fields are there, while allowing the file to include more than the minimum. I suppose that's possible today by specifying default values, but you do have to enumerate all the allowed keys.

Perhaps this concept is more relevant to data validation in a data pipeline than to configuration validation.

I'll close this issue. If I start using StrictYAML and come across a compelling use case for this feature, I'll return to it.

**Comment by nchammas** [comment]
On that note, the docs are very well-written and make the case for StrictYAML clearly and thoroughly. One thing I am missing, though, is a reference page similar to the [Python standard library docs](https://docs.python.org/3/library/json.html). I couldn't find anything like that. Did I just miss it?

**Comment by crdoconnor** [comment]
Do you mean other than the section under how to?

**Comment by nchammas** [comment]
Yes, I mean a plain reference document that just lists the available functions and what they do. The same information is available already in the docs in a more tutorial-like prose, which is good. I was just expecting the standard reference docs, too. It's not a big deal.

**Comment by crdoconnor** [comment]
I'll consider doing that too.

**Comment by nchammas** [comment]
To add a little more support for this idea, I just discovered the `additionalProperties` attribute of [JSON Schema](https://json-schema.org) via Snowplow's [SchemaVer blog post](https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/). When specified, this attribute allows data conforming to the schema specification to include additional attributes not explicitly specified in the schema.

I mention it here as independent validation that the idea captured in this issue has real-world utility, in case you revisit this issue in the future. I do not myself use StrictYAML today.

**Comment by AndydeCleyre** [comment]
Another outside example: the long gone (RIP) [obiwan](https://github.com/williame/obiwan#validating-dictionaries-and-lists) type and validation library, which allowed unmentioned additional keys, unless `strict` was specified:

> Dict templates can have a special *options* key which is a list of options. Options include *strict* and *subtype*...

> *Strict* will complain if the dictionary being validated contains any keys *not* in the template dictionary, and *subtype* will combine parameters specified in other dictionary templates with this template.
