### ISSUE TITLE
Scalars as mapping key are interpreted as non-strings without validator

### ISSUE THREAD

**Issue by gvx** [crdoconnor/strictyaml#9]
```
strictyaml.load("""
42: 42
2.0: 2.0
null: null
2016-02-01: 2016-02-01
true: true
""")
```

The result is `{True: 'True', 42: '42', None: '', 2.0: '2.0', datetime.date(2016, 2, 1): '2016-02-01'}`

Additionally, `null` is parsed as the empty string when it is a mapping or sequence value, and `true` and `false` are capitalized.

**Comment by crdoconnor** [comment]
Ouch, this is embarrassing.

**Comment by gvx** [comment]
Oh, and the same thing seems to happen recursively if the key is a sequence.

**Comment by crdoconnor** [comment]
Original bug fixed in https://github.com/crdoconnor/strictyaml/commit/c4d4ec31ad29c3383ad7e48bace059cafd9f23c2 and released on pypi as version 0.3.2.

**Comment by crdoconnor** [comment]
>Oh, and the same thing seems to happen recursively if the key is a sequence.

Do you have an example?

**Comment by gvx** [comment]
Before the fix:

    >>> strictyaml.load('[1,2]: 3')
    {(1, 2): '3'}

... but that commit fixed that issue as well.

**Comment by crdoconnor** [comment]
That shouldn't have happened either. Flow style is disallowed. That's been fixed too now.
