### ISSUE TITLE
Output ordinary dict?

### ISSUE THREAD

**Issue by aronchick** [crdoconnor/strictyaml#91]
I know that strictyaml is designed to be a drop in replacement for ruamel, which is great and definitely meets my needs.

Unforunately, strictyaml has a complicated structure for representing the yaml once parsed (which is understandable), but it prevents it from being a drop in replacement. Here's the scenario that I'm currently running into.

I'm using cerberus to do schema processing, and it requires yaml to be loaded into a dict. It looks like this:

```
# Sample yaml (as text)
schema_text = """
storage_connection_type: 
    type: string
    allowed:
        - 'AWS_BLOB', # AWS Blob"""
```

Load the yaml text into ruamel and it represents it as an ordinary dict.
```
import ruamel
parsed_yaml = ruamel.yaml.load(schema_text)
print(parsed_yaml)
# Output => {'schema_version': {'type': 'semver', 'required': True}, 'run_id': {'type': 'uuid', 'required': True}, 'step_id': {'type': 'uuid', 'required': True}, 'run_date': {'type': 'datetime', 'required': True}}
```

This dict can then be assigned to the schema in cerberus.
```
from cerberus import Validator
v = Validator()
v.schema = parsed_yaml
print(v.schema)
# Output => {'schema_version': {'type': 'semver', 'required': True}, 'run_id': {'type': 'uuid', 'required': True}, 'step_id': {'type': 'uuid', 'required': True}, 'run_date': {'type': 'datetime', 'required': True
}}
```

When I try the same thing with strictyaml, this is the result.
```
import strictyaml
strictyaml_parsed_yaml = strictyaml.load(schema_text)
strictyaml_parsed_yaml

# Output => YAML(OrderedDict([('schema_version', OrderedDict([('type', 'semver'), ('required', 'true')])), ('run_id', OrderedDict([('type', 'uuid'), ('required', 'true')])), ('step_id', OrderedDict([('type', 'uu
id'), ('required', 'true')])), ('run_date', OrderedDict([('type', 'datetime'), ('required', 'true')]))]))
```

When I try to do the same thing as above with cerberus, it fails
```
from cerberus import Validator
v = Validator()
v.schema = strictyaml_parsed_yaml
# Output => TypeError: unhashable type: 'CommentedMap'
```

Is there a way to output a generic flat dict from the object being maintained by strictyaml?

**Comment by crdoconnor** [comment]
Use .data?

**Comment by crdoconnor** [comment]
It will output OrderedDict in place of a regular dict, but it will function in a pretty much identical way to a regular dict for versions of python above 3.6.

**Comment by aronchick** [comment]
That worked - thanks! Just missed it in the docs. I'll be happy to write that up if you can point me where you'd like it :)
