### ISSUE TITLE
Casting strings as Booleans

### ISSUE THREAD

**Issue by aronchick** [crdoconnor/strictyaml#92]
Running into an issue with booleans being cast as strings intstead of booleans. The example is this:

```
UUID = """
run_id:
    type: uuid
    required: True
"""
a = strictyaml.load(UUID).data
# Value of a => OrderedDict([('run_id',
#                   OrderedDict([('type', 'uuid'), ('required', 'True')]))])

b = ruamel.YAML.load(UUID)
# Value of b => {'run_id': {'type': 'uuid', 'required': True}}

```

Notice in the first case, it cast "True" as a string, and in the second, as a boolean (the latter is correct). Is there anything I can do to fix this?

**Comment by crdoconnor** [comment]
You can use a schema. There's an example on the front page (it uses Int, but you can just swap that out with Bool).

Why it behaves this way is documented here: https://hitchdev.com/strictyaml/why/implicit-typing-removed/

**Comment by aronchick** [comment]
Oh this makes sense - do i have to have a schema for the whole file? I'd prefer just do do it for each field that may be ambiguous.

**Comment by crdoconnor** [comment]
It's encouraged that you create a schema for a whole file as that would help you detect invalid YAML much more quickly (e.g. keys missing, keys that are there but shouldn't be). You can use the Any() validator for portions of the file which you want to parse as only list/map/strings though.

Big fan of kubeflow, btw :)
