### ISSUE TITLE
Seq(Float() | Int() always evaluates to Float()

### ISSUE THREAD

**Issue by ArneBachmannDLR** [crdoconnor/strictyaml#97]
```python
>>> loadYaml('[1, 1.0]', "Seq(Float() | Int())")
[1.0, 1.0]
```

but should be `[1, 1.0]`.

The same works for non-`Seq()` definitions.

**Comment by crdoconnor** [comment]
I think you might need FixedSeq([Float(), Int()])  ?

**Comment by crdoconnor** [comment]
The | operator always resolves to the first validator's output if it
matches first.

**Comment by ArneBachmannDLR** [comment]
OK, got it working by reversing the order of elements:
```python
>>> loadYaml('[1, 1.0]', "Seq(Int () | Float())")
[1, 1.0]
```

**Comment by crdoconnor** [comment]
If your preference is that it resolves to an Int first and Float only if
it's not an int then that's the way to do it, yep.
